#!/bin/bash
file="$HOME/worklog"
icon='/usr/share/icons/gnome/32x32/apps/accessories-text-editor.png'
interval=$((60*60))
maxwait=$((30*60))
emptyretry=$((5*60))
timeoutretry=$((30*60))
showdayafter=$((20*60*60))
showdateafter=$((6*24*60*60))

gui() {
	# invalid parent makes the dialog standalone.
	# Silence warnings about the parent hack and gtk theme.
	zenity --attach 99999 --window-icon "$icon" "$@" 2>/dev/null
}

# TODO more arguments for settings or interactive
if [[ $# -eq 1 ]]; then
	file="$1"
elif [[ $# -gt 1 ]]; then
	echo "Usage: $0 [file]" >&2;
	exit 2;
fi

# use modification date of $file and fall back to one hour ago
# modification date might get clobbered, but this is simpler and less brittle
# than parsing the file.
last_u=`date '+%s' --reference "$file" 2>/dev/null \
	|| date '+%s' --date='1 hour ago'`

while true; do
	asked_u=`date '+%s'`
	asked_f=`date '+%H:%M' "--date=@$asked_u"`
	title="Worklog $asked_f" # long titles would be truncated,
	# making the window wider doesn't increase the length of the text box

	seconds=$(($asked_u-$last_u))
	if [[ $seconds -ge $showdateafter || $seconds -lt 0 ]]; then
		format='+%A %-d. %B %H:%M'
	elif [[ $seconds -ge $showdayafter ]]; then
		format='+%H:%M on %A'
	else
		format='+%H:%M'
	fi
	last_f=`date "$format" "--date=@$last_u"`
	text="What have you been doing since $last_f?"

	did=`gui --entry --title "$title" --text "$text" --timeout $maxwait \
	                 --ok-label 'Save' --cancel-label 'Wait'`
	                 # seems like I accidentally hit cancel a few times
	ret=$? # save exit code
	answered_u=`date '+%s'`
	echo -n "$ret; "
	if [[ $ret -eq 5 ]]; then # timeout
		sleep $timeoutretry
	elif [[ -z "$did" ]]; then # canceled -> snooze
		sleep $emptyretry
	elif [[ "${did:0:5}" == 'wait ' ]]; then # custom snooze
		sleep ${did:5}m 2>/dev/null \
			|| gui --error --text "minutes: \"${did:5}\" is not a positive number"
	else
		from=`date '+%d/%m %H:%M' --date "@$last_u"`
		to=`date '+%d/%m %H:%M' --date "@$answered_u"`
		echo "$from - $to: $did"
		echo "$from - $to: $did" >> "$file"
		if [ $? -ne 0 ]; then
			gui --error --text "Cannot write to \"$file\", stopping!"
			# discard the message
			exit 1
		fi
		last_u=$answered_u
		sleep $interval
	fi
done
