#!/bin/bash
file="$HOME/worklog"
interval=$((60*60))
maxwait=$((30*60))
emptyretry=$((5*60))
timeoutretry=$((30*60))
showdayafter=$((20*60*60))

# TODO arguments for settings or interactive

gui() {
	# invalid parent makes the dialog standalone.
	# Silence warnings about the parent hack and gtk theme.
	zenity --attach 99999 "$@" 2>/dev/null
}

touch "$file" 2>/dev/null || {
	gui --error "Cannot create or modify \"$file\""
	exit 1
}
last_u=`date '+%s'`

while true; do
	last_f=`date '+%H:%M' "--date=@$last_u"`
	text="What have you been doing since $last_f?"
	asked_u=`date '+%s'`
	if [ $(($asked_u-$last_u)) -ge $showdayafter ]; then # add weekday
		last_f=`date '+%H:%M on %A' "--date=@$last_f"`
	fi
	asked_f=`date '+%H:%M' "--date=@$asked_u"`
	title="Worklog $asked_f" # long titles would be truncated,
	# making the window wider doesn't increase the length of the text box

	did=`gui --entry --title "$title" --text "$text" --timeout $maxwait \
	                 --ok-label 'Save' --cancel-label 'Wait'`
	                 # seems like I accidentally hit cancel a few times
	ret=$? # save exit code
	answered_u=`date '+%s'`
	echo -n "$ret; "
	if [ $ret -eq 5 ]; then # timeout
		sleep $timeoutretry
	elif [[ -z "$did" ]]; then # canceled -> snooze
		sleep $emptyretry
	elif [[ "${did:0:5}" == 'wait ' ]]; then # custom snooze
		sleep ${did:5}m 2>/dev/null \
			|| gui --error --text "minutes: \"${did:5}\" is not a positive number"
	else
		from=`date '+%d/%m %H:%M' --date "@$last_u"`
		to=`date '+%d/%m %H:%M' --date "@$answered_u"`
		echo "$from - $to: $did"
		echo "$from - $to: $did" >> "$file"
		if [ $? -ne 0 ]; then
			gui --error --text "Cannot write to \"$file\"!"
			# discard it
		else
			last_u=$answered_u
		fi
		sleep $interval
	fi
done
